wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.9.5
    cli_version: 0.15.4
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686517375.861144
    t:
      1:
      - 55
      2:
      - 55
      3:
      - 2
      - 23
      4: 3.9.5
      5: 0.15.4
      8:
      - 5
      - 13
