wandb_version: 1

_metadata:
  desc: null
  value: 'ContainerMetadata(ref_type=typing.Any, object_type=<class ''dict''>, optional=True,
    key=None, flags={''struct'': True}, flags_root=False, resolver_cache=defaultdict(<class
    ''dict''>, {''now'': {(''%Y-%m-%d'',): ''2023-06-12'', (''%H-%M-%S'',): ''00-15-46''}}),
    key_type=typing.Any, element_type=typing.Any)'
_parent:
  desc: null
  value: null
_flags_cache:
  desc: null
  value:
    struct: true
_content:
  desc: null
  value:
    classifier: '{''_target_'': ''xgboost.XGBClassifier'', ''learning_rate'': 0.1,
      ''gamma'': 0.3, ''max_depth'': 9, ''min_child_weight'': 4, ''max_delta_step'':
      2, ''subsample'': 0.6, ''colsample_bytree'': 0.8, ''lambda'': 0.2, ''tree_method'':
      ''hist'', ''grow_policy'': ''lossguide'', ''max_leaves'': 3}'
    adapt_model: '{''_target_'': ''adapt.instance_based.KMM'', ''kernel'': ''laplacian'',
      ''B'': 500, ''eps'': 0.0001, ''max_size'': 500, ''tol'': 1e-06, ''max_iter'':
      800, ''verbose'': 0}'
    wandb: '{''project'': ''cross-adaptation'', ''entity'': ''thelion-ai''}'
    random_state: '42'
    root_path: ../../../../experiments/data/interim/train
    train_data: '{''Brazil-1'': ''Brazil-1.csv'', ''Brazil-2'': ''Brazil-2.csv'',
      ''Italy-1'': ''Italy-1.csv'', ''Italy-2'': ''Italy-2.csv'', ''italy-3'': ''Italy-3.csv'',
      ''Poland'': ''Poland.csv''}'
    test_data: '{''Spain'': ''Spain.csv'', ''Italy'': ''Italy-3.csv''}'
    metrics:
    - '{''_target_'': ''sklearn.metrics.accuracy_score''}'
    - '{''_target_'': ''sklearn.metrics.f1_score''}'
    - '{''_target_'': ''sklearn.metrics.roc_auc_score''}'
    - '{''_target_'': ''sklearn.metrics.precision_score''}'
    - '{''_target_'': ''sklearn.metrics.recall_score''}'
    optimized_metric: f1_score
_wandb:
  desc: null
  value:
    python_version: 3.9.5
    cli_version: 0.15.4
    framework: xgboost
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1686521748.033407
    t:
      1:
      - 2
      - 3
      - 5
      - 35
      - 50
      - 53
      - 55
      2:
      - 2
      - 3
      - 5
      - 6
      - 35
      - 50
      - 53
      - 55
      3:
      - 16
      - 23
      - 24
      4: 3.9.5
      5: 0.15.4
      8:
      - 5
