_target_: xgboost.XGBClassifier
learning_rate: 0.1
gamma: 0
max_depth: 3
min_child_weight: 1
max_delta_step: 0
subsample: 0.6
colsample_bytree: 0.6
lambda: 0
tree_method: 'auto'
grow_policy: 'depthwise'
max_leaves: 0
