classifier.n_estimators: choice(100, 200, 300, 400, 500, 600, 700, 800, 900, 1000)
classifier.criterion: choice('gini', 'entropy')
classifier.max_depth: choice(5, 10, 15, 20, 25, 30, 35, 40, 45, 50)
classifier.min_samples_split: choice(2, 5, 10, 15, 20)
classifier.min_samples_leaf: choice(1, 2, 4, 6, 8, 10)
# classifier.min_weight_fraction_leaf: uniform(0.0, 0.5)
classifier.max_features: choice('auto', 'sqrt', 'log2')
classifier.max_leaf_nodes: choice(5, 10, 20, 50, 100)
# classifier.min_impurity_decrease: uniform(0.0, 0.5)
classifier.oob_score: choice(True, False)
# classifier.ccp_alpha: uniform(0.0, 0.5)
# classifier.max_samples: uniform(0.0, 1.0)